### ISSUE TITLE
Not able to access via developer portal

### ISSUE THREAD

**Issue by bqkhiem96** [RightMesh/meshIM#1]
I've registered for the account but no confirmation has been sent to my email

**Comment by compscidr** [comment]
For account verification, check your junk mail folder - often they get sent there.

That being said, the sample code is being put up for developers at hackathon to use - we aren't opening it for general use at this time because we won't be able to support everyone who wants to give it a try. Creating an account should let you see more of the documentation (javadocs, some more sample code, etc.) but you won't be able to get access to the library itself at this time.

**Comment by bqkhiem96** [comment]
Thanks for the information. Glad to see RightMesh is growing.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>
