### ISSUE TITLE
Add the device's user information somewhere on the online users list.

### ISSUE THREAD

**Issue by compscidr** [RightMesh/meshIM#9]
It is difficult to tell which phone the given phone is - it would be nice if somewhere on the contact list there was something that indicated which phone the current one is without having to click the account page.

**Comment by FrazerSeymour** [comment]
@JMortemore - I'm wondering about putting their avatar in the action bar, on the right. Do you or @llefurgeysmith  have thoughts on how we could do this?

**Comment by JMortemore** [comment]
@FrazerSeymour Personally not crazy about the idea, because we already have an account tab that displays this. If you added it there, it's typically associated with an action, like opening to your account, which would be redundant here. Also, I think the case that is being experienced here is one that is specific to testing internally. So with that in mind, sure if we need it for ourselves, but not for public release.

**Comment by FrazerSeymour** [comment]
Yeah I was thinking the same thing (RE adding a testing feature to a public app), and your logic makes sense fr not putting it in the action bar. We can maybe do it in a separate branch and build from there for testing.

Would there be any merit to putting your avatar as the icon in the account tab? My only thought against that would be it could get weird branding-wise when we let people do profile pictures.

**Comment by JMortemore** [comment]
Agreed with all of the above. I don't think we need the avatar in the footer.
